version: '3.8'

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true

services:
  jenkins:
    environment:
      - VIRTUAL_HOST=${HOST_JENKINS}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${HOST_JENKINS}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - nginx-proxy