version: "3.8"
networks:
  pgadmin:
    name: pgadmin

services:
  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - "5052:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pgadmin

volumes:
  pgadmin-data: