version: '3.8'

services:
  ssh-agent:
    image: jenkins/ssh-agent:jdk11
    container_name: ssh-agent
    restart: unless-stopped
    hostname: ssh-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_PUB_KEY}
